apiVersion: apps/v1
kind: Deployment
metadata:
  name: create
  labels:
    app: create
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create
  template:
    metadata:
      labels:
        app: create
    spec:
      containers:
        - name: create
          image: "username/create:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
