---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: create
  labels:
    app: create
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create
  template:
    metadata:
      labels:
        app: create
    spec:
      containers:
        - name: create
          image: username/create:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspection
  labels:
    app: inspection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inspection
  template:
    metadata:
      labels:
        app: inspection
    spec:
      containers:
        - name: inspection
          image: username/inspection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: create
  labels:
    app: create
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: create


---


apiVersion: v1
kind: Service
metadata:
  name: inspection
  labels:
    app: inspection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: inspection

